model = "gpt-5.6-sol"
model_reasoning_effort = "medium"

approval_policy = "never"
sandbox_mode = "danger-full-access"
personality = "pragmatic"




approvals_reviewer = "user"
service_tier = "default"


notify = ["/Users/cgas/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/cgas/Documents/Projects/Atelier"]
trust_level = "trusted"

[projects."/Users/cgas"]
trust_level = "trusted"

[projects."/Users/cgas/.codex"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/darktableAgent"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/OpenCodePlugins"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/resume"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/Atelier2"]
trust_level = "trusted"

[projects."/Users/cgas/.config/opencode"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/rapidRawAgent"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/vkdtAgent"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/anselAgent"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/vkdtUi"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Projects/capture-one-mcp"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-19-what-should-i-expect-to-come"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-20-why-does-this-error-keep-happening"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-20-computer-use-plugin-computer-use-openai"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-20-can-this-be-used-to-have"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-20-can-you-see-in-my-documents"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-25/computer-use-plugin-computer-use-openai"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-25/browser-use-plugin-browser-use-openai"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-26/https-cua-ai-docs-cua-driver"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-26/browser-use-plugin-browser-use-openai"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-26/what-is-opencode-oool-call-pruning"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-04-29/generate-an-image-with-4-polo"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-04/can-you-look-at-my-memory"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-04/for-this-codex-should-we-change"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-04/computer-plugin-computer-use-openai-bundled"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-05/can-you-get-the-goal-command"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-05/can-you-add-a-new-global"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-06/browser-plugin-browser-use-openai-bundled"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-06/can-you-set-this-up-on"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-06/copilot-plugin-copilot-local-projects-go"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-06/explain-to-me-the-codex-goal"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-06/plugin-creator-users-cgas-codex-skills"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-08/chrome-plugin-chrome-openai-bundled-can"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-08/files-mentioned-by-the-user-img"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-08/how-tall-is-wemby"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-08/capture-one-plugin-computer-use-openai"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-08/chrome-plugin-chrome-openai-bundled-find"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-08/chrome-plugin-chrome-openai-bundled-find-2"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-09/search-japenese-sites-for-a-great"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-11/are-there-any-open-source-programs"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-13/gmail-plugin-gmail-openai-curated-google"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-14/chrome-chrome-users-cgas-codex-plugins"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-14/it-feels-like-your-context-is"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-14/help-me-out-on-this-features"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-15/how-do-i-set-this-up"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-19/chrome-plugin-chrome-openai-bundled-computer"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-20/google-drive-plugin-google-drive-openai"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-21/chrome-plugin-chrome-openai-bundled-find"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-21/applications-mentioned-by-the-user-appshot"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-23/applications-mentioned-by-the-user-appshot"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-23/on-my-windows-desktop-i-just"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-26/chrome-plugin-chrome-openai-bundled-im"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-26/computer-plugin-computer-use-openai-bundled"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-26/why-is-this-session-making-me"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-27/amazon-support-browser-users-cgas-codex"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-27/chrome-plugin-chrome-openai-bundled-i"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Cameras"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-31/chrome-plugin-chrome-openai-bundled-i"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-31/has-anyone-pirated-capture-one-for"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-05-31/computer-plugin-computer-use-openai-bundled"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-01/will-i-be-able-to-use"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-01/browser-plugin-browser-openai-bundled-find"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-01/browser-plugin-browser-openai-bundled-go"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-03/look-at-the-skill-instructions-for"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-03/can-you-download-claude-cli-then"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-03/how-are-you-claude"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-03/how-are-you-claude-2"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-03/chrome-plugin-chrome-openai-bundled-i"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-03/are-you-able-to-interact-easier"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-04/chrome-plugin-chrome-openai-bundled-shop"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-05/update-your-global-consult-skill-with"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-05/is-npm-on-path-if-not"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-08/i-just-got-offered-to-resign"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-08/can-i-create-a-photography-gallery"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-09/brave-browser-plugin-computer-use-openai"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-09/files-mentioned-by-the-user-codex"]
trust_level = "trusted"

[projects."/private/tmp"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-09/you-there"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/RawEngine"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-10/make-an-update-to-the-conslut"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-10/applications-mentioned-by-the-user-appshot"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-11/can-you-make-a-new-repo"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-11/are-you-there"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-11/you-there"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-11/messages-plugin-computer-use-openai-bundled"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-13/i-have-a-very-long-running"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-17/does-the-person-need-to-sign"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-17/it-looks-like-my-rate-limits"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-17/in-app-browser-the-user-has"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-17/is-there-any-friction-this-agent"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-18/how-many-tokens-has-this-session"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-18/i-want-you-to-start-using"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-19/are"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-19/loo"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-19/c"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-20/com"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-21/c"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-21/esti"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-22/updat"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-22/how"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-25/w"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-25/lo"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/RawEngine/RapidRaw"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-28/is"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-29/this"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-29/upda"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-29/updat"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-29/i"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-30/un"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-06-30/how"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-05/aw"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-06/new-chat"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-07/new-chat"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-09/lo"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-09/w"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-09/in"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-09/run"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-09/consult-users-cgas-codex-skills-consult"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-10/lo"]
trust_level = "trusted"

[projects."/Users/cgas/Documents/Codex/2026-07-10/can"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true
suppress_unstable_features_warning = true
fast_default_opt_out = true

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[features]
multi_agent = true
responses_websockets_v2 = true
memories = false
prevent_idle_sleep = true
goals = true

hooks = true
chronicle = false
js_repl = false

[marketplaces.openai-bundled]
last_updated = "2026-07-10T12:29:19Z"
source_type = "local"
source = "/Users/cgas/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-10T02:02:44Z"
source_type = "local"
source = "/Users/cgas/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.local-projects]
last_updated = "2026-05-06T05:58:38Z"
source_type = "local"
source = "/Users/cgas/Documents/Projects"

[plugins."github@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[desktop]
ambient-suggestions-enabled = false
appearanceLightCodeThemeId = "absolutely"
usePointerCursors = false
followUpQueueMode = "steer"
composerEnterBehavior = "enter"
reviewDelivery = "inline"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-create-pull-request-as-draft = false
git-pull-request-merge-method = "squash"
git-show-sidebar-pr-icons = true
git-pr-instructions = "Pull requests should include a how and a why section. the why section should sell on why the pull request benefits the project"
selected-avatar-id = "custom:mishka"
default-service-tier = "priority"
show-context-window-usage = true
appearanceTheme = "dark"
appearanceDarkCodeThemeId = "monokai"
dock-icon-preference = "codex-system"
conversationDetailMode = "STEPS_COMMANDS"
computerUseAlwaysHidePictureInPicture = true

[desktop.appearanceLightChromeTheme]
accent = "#cc7d5e"
contrast = 45
ink = "#2d2d2b"
opaqueWindows = false
surface = "#f9f9f7"

[desktop.appearanceLightChromeTheme.fonts]

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00c853"
diffRemoved = "#ff5f38"
skill = "#cc7d5e"

[desktop.appearanceDarkChromeTheme]
accent = "#99947c"
contrast = 60
ink = "#f8f8f2"
opaqueWindows = false
surface = "#272822"

[desktop.appearanceDarkChromeTheme.fonts]

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#86b42b"
diffRemoved = "#c4265e"
skill = "#8c6bc8"

[hooks.state]

[hooks.state."/Users/cgas/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:5a6bc80af6b27ea839863b0445d4c4cee362abbf5cac4152363fa14c3a5e6a13"

[mcp_servers.aws_mcp]
command = "/opt/homebrew/bin/uvx"
args = ["mcp-proxy-for-aws@latest", "https://aws-mcp.us-east-1.api.aws/mcp", "--profile", "aws-mcp-readonly", "--region", "us-east-1", "--metadata", "AWS_REGION=us-east-1"]
startup_timeout_sec = 120.0

[mcp_servers.aws_mcp.env]
AWS_DEFAULT_REGION = "us-east-1"
AWS_PROFILE = "aws-mcp-readonly"
AWS_REGION = "us-east-1"

[mcp_servers.node_repl]
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120.0

[mcp_servers.node_repl.env]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.31428"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"
CODEX_HOME = "/Users/cgas/.codex"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,c8b7e809d7cf9e20a57123b2530d476ccec9a01a6230a7b2b924fea7d94d7f4a"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/cgas/.codex"
SKY_CUA_SERVICE_PATH = "/Users/cgas/.codex/plugins/cache/openai-bundled/computer-use/1.0.1000366/Codex Computer Use.app"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[memories]
generate_memories = false
use_memories = false

[apps.connector_openai_codex_document_control]
enabled = false

[apps.connector_691eab1e001081919e57189f8b2f03bc]
enabled = false
